name: Django CI

on:
  push:
    branches:
      - main
      - feat/*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Build and start services
        run: |
          docker-compose up -d --build
          echo "Waiting for PostgreSQL to be ready..."
          # espera o PostgreSQL aceitar conexões
          until docker exec db pg_isready -U myuser -d mydatabase; do
            sleep 2
          done

      - name: Run migrations
        run: |
          docker-compose exec web codeleap/python manage.py migrate --noinput

      - name: Run tests
        run: |
          docker-compose exec web pytest --disable-warnings

      - name: Stop services
        if: always()
        run: docker-compose down
