name: Django CI

on:
  push:
    branches:
      - main
      - feat/*
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U myuser -d mydatabase"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://myuser:mypassword@localhost:5432/mydatabase
      SECRET_KEY: test-secret-key
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U myuser; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Apply migrations
        run: |
          source venv/bin/activate
          python codeleap/manage.py migrate --noinput

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --disable-warnings --maxfail=1
